name: Simple Listener
run-name: Listen items_game.txt file
on:
  workflow_dispatch:
#   schedule:
#     - cron:  '0 0/3 * * *'

jobs:
  listen:
    name: Listen to file
    runs-on: ubuntu-latest
    steps:
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/SteamDatabase/GameTracking-Dota2/contents/game/dota/pak01_dir/scripts/items/items_game.txt | \
          jq -r ".sha" > current_version.txt

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: "completed"
          name: my-artifact
          if_no_artifact_found: ignore
          workflow: other-listener.yml

      - name: Compare files
        id: compare
        if: always()
        run: |
          echo modified=$([ -z "`diff artifact_version.txt current_version.txt`" ] && echo "false" || echo "true") >> $GITHUB_OUTPUT

#       - name: Launch workflow
#         if: ${{ steps.compare.outputs.modified == 'true' }} 
#         uses: ./.github/workflows/simple-downloader.yml

      - name: Write to artifact
        if: always()
        run: |
          cat current_version.txt > artifact_version.txt
#          echo $(date +%Y-%m-%d-%H:%M) >> artifact_version.txt

      - name: Store data
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: artifact_version.txt
          retention-days: 1
